export const BLOG_POPULATE_ARTICLES = 'BLOG_POPULATE_ARTICLES';
export const BLOG_GET_ARTICLE_CONTENT = 'BLOG_GET_ARTICLE_CONTENT';

export const TESTIMONIALS_POPULATE_TESTIMONIALS = 'TESTIMONIALS_POPULATE_TESTIMONIALS';
